language: ruby
rvm:
  - 2.3.1
before_script:
  - gem install awesome_bot
script:
  - awesome_bot program-list/program-list.json --allow-dupe --white-list travis-ci --allow-redirect --allow-timeout -t 5 --allow 403
