name: validate-program-list

on:
  push:
    paths:
      - 'program-list.json'
      - 'program-list-schema.json'
      - '.github/**'
  pull_request:
    paths:
      - 'program-list.json'
      - 'program-list-schema.json'
      - '.github/**'

permissions: read-all

jobs:
  duplicate_check_job:
    runs-on: ubuntu-latest
    name: duplicate-check job
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: duplicate-check action step
      uses: ./.github/actions/duplicate-check

  validate_json_fix_job:
    runs-on: ubuntu-latest
    name: validate-json job
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: validate-json action step
      uses: ./.github/actions/validate-json

  validate_links_job:
    runs-on: ubuntu-latest
    name: validate-links job
    if: false
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install dependencies
      run: npm ci
      working-directory: ./.github/actions/validate-links
    - name: validate-links action step
      uses: ./.github/actions/validate-links

  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/validate-format
