name: validate-program-list

on:
  push:
    paths:
      - 'program-list.json'
      - 'program-list-schema.json'
      - '.github/**'
  pull_request:
    paths:
      - 'program-list.json'
      - 'program-list-schema.json'
      - '.github/**'

permissions: read-all

jobs:
  duplicate_check_job:
    runs-on: ubuntu-latest
    name: duplicate-check job
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: duplicate-check action step
      uses: ./.github/actions/duplicate-check

  validate_json_fix_job:
    runs-on: ubuntu-latest
    name: validate-json job
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: validate-json action step
      uses: ./.github/actions/validate-json

  validate_links_job:
    runs-on: ubuntu-latest
    name: validate-links job
    if: false
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install dependencies
      run: npm ci
      working-directory: ./.github/actions/validate-links
    - name: validate-links action step
      uses: ./.github/actions/validate-links

  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/validate-format

  feedback:
    needs: [duplicate_check_job, validate_json_fix_job, validate_links_job, format]
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    if: failure()
    steps:
      - uses: peter-evans/create-or-update-comment@c9fcb64660bc90ec1cc535646af190c992007c32 # v2.0.0
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            Some of the automated checkes have failed. Passing the checks is required to merge the pull request. Please see annotations at https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }} for details and steps to remediate the issue(s).
